import React from 'react';
import { withRouter } from 'react-router';
import { Layout, Input, message } from 'antd';
import { UserContext } from '../context/UserContext';

const { Content } = Layout;

class Home extends React.Component {
  static contextType = UserContext;

  componentDidUpdate() {
    if (this.context.my_chat_id !== null) {
      this.props.history.push(`/rooms/${this.context.my_chat_id}`);
    }
  }

  render() {
    return (
      <Content style={{ margin: '24px 16px 0', overflow: 'initial' }}>
        <div className="list-message">
          ...
          <br />
          Really
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          long
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          content long
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          content
        </div>
        <Input.TextArea placeholder="Typing in here !!!" rows={4} style={{ resize: 'none' }} />
      </Content>
    );
  }
}

export default withRouter(Home);
