export const INVATATION_STATUS = {
  IN_ROOM: 700,
  JOIN_AS_MEMEBER: 701,
  HAVE_REQUEST_BEFORE: 702,
  CANT_JOIN: 703,
};

export const ROOM_TYPE = {
  GROUP_CHAT: 0,
};

export const LIMIT_REPRESENTATIVE_MEMBER = 5;
