export const INVATATION_STATUS = {
  IN_ROOM: 700,
  JOIN_AS_MEMEBER: 701,
  HAVE_REQUEST_BEFORE: 702,
  CANT_JOIN: 703,
};

export const ROOM_TYPE = {
  GROUP_CHAT: 0,
  DIRECT_CHAT: 1,
  MY_CHAT: 2,
};

export const LIMIT_REPRESENTATIVE_MEMBER = 5;
export const MESSAGE_PAGINATE = 10;
export const VISIABLE_MSG_TO_LOAD = 4;
export const LIMIT_QUANLITY_NEWEST_MSG = 200;
export const NUMBER_REQUEST_JOIN_ROOM_OVERFLOW = 99;
